"""item modue

Revision ID: 51fe1548755f
Revises: 5c0506f1800d
Create Date: 2026-08-15 02:59:45.259168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51fe1548755f'
down_revision: Union[str, Sequence[str], None] = '5c0506f1800d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('date_occurred', sa.DATE(), nullable=True))
    op.drop_column('items', 'date_occerred')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('date_occerred', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('items', 'date_occurred')
    # ### end Alembic commands ###
