"""item modue

Revision ID: 5c0506f1800d
Revises: 6b945680c5ea
Create Date: 2026-08-15 00:06:45.614801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c0506f1800d'
down_revision: Union[str, Sequence[str], None] = '6b945680c5ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('item_type', sa.Enum('lost', 'found', name='item_type'), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('date_occerred', sa.DATE(), nullable=True),
    sa.Column('status', sa.Enum('active', 'recovered', 'returned', name='statuscheck'), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('items')
    # ### end Alembic commands ###
