"""image module

Revision ID: 610578707a2c
Revises: e82786e141fc
Create Date: 2026-08-16 04:19:36.638360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '610578707a2c'
down_revision: Union[str, Sequence[str], None] = 'e82786e141fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('file_path', sa.String(), nullable=True))
    op.add_column('images', sa.Column('original_filename', sa.String(), nullable=True))
    op.add_column('images', sa.Column('new_filename', sa.String(), nullable=True))
    op.drop_column('images', 'image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('images', 'new_filename')
    op.drop_column('images', 'original_filename')
    op.drop_column('images', 'file_path')
    # ### end Alembic commands ###
