""" usermodel

Revision ID: 6bcf36ca68ad
Revises: ae0a87ff0b18
Create Date: 2026-08-10 20:48:49.148649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bcf36ca68ad'
down_revision: Union[str, Sequence[str], None] = 'ae0a87ff0b18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('revokedtokens', sa.Column('expire_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('revokedtokens', 'expire_at')
    # ### end Alembic commands ###
