"""image module

Revision ID: dce7ec52a674
Revises: acc6941ab5ac
Create Date: 2026-08-16 05:19:53.817541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dce7ec52a674'
down_revision: Union[str, Sequence[str], None] = 'acc6941ab5ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('image_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'items', 'images', ['image_id'], ['id'], ondelete='CASCADE')
    op.drop_column('items', 'image')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.drop_column('items', 'image_id')
    # ### end Alembic commands ###
